### ISSUE TITLE
Cannot initialize app in v4

### ISSUE THREAD

**Issue by inakijaneiro** [remix-pwa/monorepo#165]
Hey there!

I'm working in a remix website and want to make it a PWA. I followed the [Quick Start docs](https://remix-pwa.run/docs/main/quick-start) but when I run `remix vite:dev --host` I get the following errors:
```
Error during worker build: SyntaxError: [vite-plugin-remix-pwa:virtual-entry-sw] Could not load virtual:entry-sw (imported by node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js): Unexpected token, expected "}" (7:16)
    at constructor (/Users/myuser/Documents/remix/myapp/node_modules/@babel/parser/lib/index.js:353:19)
    at TypeScriptParserMixin.raise (/Users/myuser/Documents/remix/myapp/node_modules/@babel/parser/lib/index.js:3277:19)
    at TypeScriptParserMixin.unexpected (/Users/myuser/Documents/remix/myapp/node_modules/@babel/parser/lib/index.js:3297:16)
    at TypeScriptParserMixin.expect (/Users/myuser/Documents/remix/myapp/node_modules/@babel/parser/lib/index.js:3601:28)
    at TypeScriptParserMixin.jsxParseExpressionContainer (/Users/myuser/Documents/remix/myapp/node_modules/@babel/parser/lib/index.js:6692:10)
    at TypeScriptParserMixin.jsxParseElementAt (/Users/myuser/Documents/remix/myapp/node_modules/@babel/parser/lib/index.js:6766:36)
    at TypeScriptParserMixin.jsxParseElement (/Users/myuser/Documents/remix/myapp/node_modules/@babel/parser/lib/index.js:6804:17)
    at TypeScriptParserMixin.parseExprAtom (/Users/myuser/Documents/remix/myapp/node_modules/@babel/parser/lib/index.js:6816:19)
    at TypeScriptParserMixin.parseExprSubscripts (/Users/myuser/Documents/remix/myapp/node_modules/@babel/parser/lib/index.js:10580:23)
    at TypeScriptParserMixin.parseUpdate (/Users/myuser/Documents/remix/myapp/node_modules/@babel/parser/lib/index.js:10563:21) {
  code: 'PLUGIN_ERROR',
  reasonCode: 'UnexpectedToken',
  loc: Position { line: 7, column: 16, index: 178 },
  pos: 178,
  pluginCode: 'BABEL_PARSER_SYNTAX_ERROR',
  plugin: 'vite-plugin-remix-pwa:virtual-entry-sw',
  hook: 'load',
  watchFiles: [
    '/Users/myuser/Documents/remix/myapp/node_modules/@remix-pwa/worker-runtime/dist/src/service-worker.internal.js'
  ]
}
```
```
Error: ENOENT: no such file or directory, open '/Users/myuser/Documents/remix/myapp/public/entry.worker.js'
    at Object.openSync (node:fs:596:3)
    at readFileSync (node:fs:464:35)
    at getWorkerHash (file:///Users/myuser/Documents/remix/myapp/node_modules/@remix-pwa/dev/dist/src/hash.js:7:17)
    at Context.buildStart (file:///Users/myuser/Documents/remix/myapp/node_modules/@remix-pwa/dev/dist/src/plugins/bundler.js:133:24)
    at async Promise.all (index 6)
    at async hookParallel (file:///Users/myuser/Documents/remix/myapp/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:50358:9)
    at async Object.buildStart (file:///Users/myuser/Documents/remix/myapp/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:50710:13)
    at async file:///Users/myuser/Documents/remix/myapp/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:64593:13
    at async httpServer.listen (file:///Users/myuser/Documents/remix/myapp/node_modules/vite/dist/node/chunks/dep-stQc5rCc.js:64611:17) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/myuser/Documents/remix/myapp/public/entry.worker.js'
}
```

If I move `entry.worker.ts` (which was generated with `npx remix-pwa sw`) into the `public` folder and  change the extension to `.js`, the second error (`no such file or directory`) seems to go away, but the first one is still there

Any ideas on how to fix it?

**Comment by inakijaneiro** [comment]
Never mind. Don't know if I did something different today but I deleted everything, installed again and it's now working (only issue I found was #158)
